# This is a config for E2B sandbox template.
# You can use template ID (zcxo3nr01udjamtzcdn4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("zcxo3nr01udjamtzcdn4") # Sync sandbox
# sandbox = await AsyncSandbox.create("zcxo3nr01udjamtzcdn4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zcxo3nr01udjamtzcdn4')

team_id = "1edde3e1-6b02-4c01-b070-b9a159e08d27"
start_cmd = "npm run dev"
dockerfile = "e2b.Dockerfile"
template_id = "zcxo3nr01udjamtzcdn4"
